server:
  port: 8090

clients:
  data: http://localhost:8092
  events: http://localhost:8091
  players: http://localhost:8100
  training:
  ml-train-result: /train/results/<country>/<from>/<to>/<receipt>
  ml-train-goals: /train/goals/<country>/<from>/<to>/<receipt>


springdoc:
  swagger-ui:
    path: /swagger-ui.html

connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-teams-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"


delays:
  interval: 1
  training: 15
  training-init: 1

training:
  evaluation: true
