server:
  port: 8105

clients:
  data: http://172.22.0.21:8103
  events: http://172.22.0.24:8106
  message: http://172.22.0.18:8100
  training: http://172.22.0.18:8100/teams
  ml-train-result: /train/results/<country>/<from>/<to>/<receipt>
  ml-train-goals: /train/goals/<country>/<from>/<to>/<receipt>


springdoc:
  swagger-ui:
    path: /swagger-ui.html

connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-teams-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
  config:
    import: "optional:configserver:http://172.31.24.130:8888"


delays:
  interval: 1
  training: 15
  training-init: 1

training:
  evaluation: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
