# general properties
server:
  port: 8106
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://172.22.0.21:8103
  event-data: http://172.22.0.22:8104
  message: http://172.22.0.18:8100
  training: http://172.22.0.18:8100/teams
  ml-predict-result: /predict/result/<country>/<receipt>
  ml-predict-goals: /predict/goals/<country>/<receipt>

connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-events-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"


delays:
  competition: 1



