# general properties
server:
  port: 8094
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://localhost:8092
  training: http://localhost
  event-data: http://localhost:8093
  players: http://localhost:8095
  client: http://localhost:8100
  ml-predict-result: /predict/result/<country>/<receipt>
  ml-predict-goals: /predict/goals/<country>/<receipt>

connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-events-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"


delays:
  competition: 1



