sportScrapers: [
{siteRules: [
{id: "events",
 url: "https://www.espn.co.uk/football/match?gameId={game_id}",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[tbodyIdx]/tr[trIdx]/td/divsubIdx/div[1]/span[spanIdx]/a/text()",
 index: "trIdx",
 ranges: [
   "{\"divIdx\": 3, \"trIdx\": 13, \"tbodyIdx\": 1, \"subIdx\": \"\", \"spanIdx\": 3 }"],
 occurs: "-1"}
]
}]
