sportScrapers: [
{siteRules: [
{id: "events",
 url: "https://www.espn.co.uk/football/matchstats?gameId={game_id}",
 active: "true",
 xpath: "/html/body/div[5]/section/section/div/div/div/div/div[1]/div[1]/div/div/div[2]/table/tbody/tr[trIdx]/td[tdIdx]",
 index: "trIdx",
 ranges: [
   "{\"key\": \"data-stat\" , \"trIdx\": 7,  \"tdIdx\": 1}",
   "{\"key\": \"data-stat\" , \"trIdx\": 7,  \"tdIdx\": 3}"],
 occurs: "-1"},
{id: "posession-home",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-soccer-match-stats\"]/div/div/div[1]/div[1]/div[3]/span[1]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "posession-away",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-soccer-match-stats\"]/div/div/div[1]/div[1]/div[3]/span[3]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "shots-home",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-soccer-match-stats\"]/div/div/div[1]/div[2]/div/div[1]/div/span/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "shots-away",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-soccer-match-stats\"]/div/div/div[1]/div[2]/div/div[2]/div/span/text()",
 index: "",
 ranges: [],
 occurs: "-1"}
]
}]
