sportScrapers: [
{siteRules: [
{id: "events",
 url: "https://www.espn.co.uk/football/match?gameId={game_id}",
 active: "true",
 xpath: "",
 index: "divIdx",
 ranges: ["{\"divIdx\": 3}"],
 occurs: "-1"},
{id: "players",
 url: "",
 active: "true",
 xpath: "",
 index: "trIdx",
 ranges: ["{\"trIdx\": 12}"],
 occurs: "-1"},
{id: "saves",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[1]/span[2]/text()",
 index: "1",
 ranges: [],
 occurs: "-1"},
{id: "goals",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[1]/span[2]/text()",
 index: "greater",
 ranges: [],
 occurs: "2"},
{id: "shotsOnTarget",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[2]/ul/li[1]/span[3]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "totalShots",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[2]/ul/li[2]/span[2]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "foulsCommited",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[3]/ul/li[1]/span[3]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "foulsSuffered",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/div[3]/ul/li[2]/span[2]/text()",
 index: "",
 ranges: [],
 occurs: "-1"},
{id: "goalAssists",
 url: "",
 active: "true",
 xpath: "//*[@id=\"gamepackage-game-lineups\"]/article/div/div[divIdx]/div/div/div/table/tbody[1]/tr[trIdx]/td/{sub}/div[2]/div/ul/li[1]/span[2]/text()",
 index: "",
 ranges: [],
 occurs: "-1"}
]
}]