sportScrapers: [
{siteRules: [
 {id: "england_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/eng.1/date/{date}",
  order: "1000",
  active: "true"},
 {id: "england_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/eng.2/date/{date}",
  order: "10001",
  active: "true"},
 {id: "england_3",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/eng.3/date/{date}",
  order: "10002",
  active: "true"},
 {id: "england_4",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/eng.4/date/{date}",
  order: "10003",
  active: "true"},
 {id: "england_5",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/eng.5/date/{date}",
  order: "10004",
  active: "true"},
 {id: "scotland_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/sco.1/date/{date}",
  order: "10005",
  active: "true"},
 {id: "scotland_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/sco.2/date/{date}",
  order: "10006",
  active: "true"},
 {id: "scotland_3",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/sco.3/date/{date}",
  order: "10007",
  active: "true"},
 {id: "scotland_4",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/sco.4/date/{date}",
  order: "10008",
  active: "true"},
 {id: "german_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/ger.1/date/{date}",
  order: "100",
  active: "true"},
 {id: "german_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/ger.2/date/{date}",
  order: "101",
  active: "true"},
 {id: "spain_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/esp.1/date/{date}",
  order: "102",
  active: "true"},
 {id: "spain_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/esp.2/date/{date}",
  order: "103",
  active: "true"},
 {id: "italy_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/ita.1/date/{date}",
  order: "104",
  active: "true"},
 {id: "italy_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/ita.2/date/{date}",
  order: "105",
  active: "true"},
 {id: "france_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/fra.1/date/{date}",
  order: "106",
  active: "true"},
 {id: "france_2",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/fra.2/date/{date}",
  order: "107",
  active: "true"},
 {id: "turkey_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/tur.1/date/{date}",
  order: "1",
  active: "true"},
 {id: "holland_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/ned.1/date/{date}",
  order: "2",
  active: "true"},
 {id: "belgium_1",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/bel.1/date/{date}",
  order: "3",
  active: "true"},
 {id: "portugal_1",
  order: "4",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/por.1/date/{date}",
  active: "true"},
 {id: "sweden_1",
  order: "5",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/swe.1/date/{date}",
  active: "true"},
 {id: "norway_1",
  order: "6",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/nor.1/date/{date}",
  active: "true"},
 {id: "denmark_1",
  order: "7",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/den.1/date/{date}",
  active: "true"},
 {id: "russia_1",
  order: "8",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/rus.1/date/{date}",
  active: "true"},
 {id: "greece_1",
  order: "9",
  url: "https://www.espn.co.uk/soccer/scoreboard/_/league/gre.1/date/{date}",
  active: "true"},
 {id: "generic",
  url: "",
  active: "true",
  xpath: "window.espn.scoreboardData",
  index: "events",
  ranges: [
   "{\"key\": \"id\",
    \"date\":
    [{\"key\": \"competitions\", \"type\": \"array\", \"index\": \"0\"},
    {\"key\": \"date\", \"type\": \"date\"}],
   \"homeScore\":
   [{\"key\": \"competitions\", \"type\": \"array\", \"index\": \"0\"},
   {\"key\": \"competitors\", \"type\": \"array\", \"index\": \"homeAway\", \"value\": \"home\"},
   {\"key\": \"score\", \"type\": \"string\"}],
   \"homeTeam\":
   [{\"key\": \"competitions\", \"type\": \"array\", \"index\": \"0\"},
   {\"key\": \"competitors\", \"type\": \"array\", \"index\": \"homeAway\", \"value\": \"home\"},
   {\"key\": \"team\", \"type\": \"object\"},
   {\"key\": \"displayName\", \"type\": \"string\"}],
   \"awayScore\":
  [{\"key\": \"competitions\",\"type\": \"array\", \"index\": \"0\"},
  {\"key\": \"competitors\",\"type\": \"array\", \"index\": \"homeAway\", \"value\": \"away\"},
  {\"key\": \"score\", \"type\": \"string\"}],
   \"awayTeam\":
  [{\"key\": \"competitions\",\"type\": \"array\", \"index\": \"0\"},
  {\"key\": \"competitors\",\"type\": \"array\", \"index\": \"homeAway\", \"value\": \"away\"},
  {\"key\": \"team\", \"type\": \"object\"},
  {\"key\": \"displayName\", \"type\": \"string\"}],
   \"details\":
   [{\"key\": \"competitions\",\"type\": \"array\", \"index\": \"0\"},
   {\"key\": \"details\", \"type\": \"array\", \"index\": \"iterate\",
   \"data\": [{\"objectKey\": \"athletesInvolved\",\"objectType\": \"array\", \"index\": \"0\",
               \"dataKey\": \"displayName\", \"dataType\": \"string\"},
              {\"objectKey\": \"clock\", \"objectType\": \"object\", \"index\": \"0\",
                             \"dataKey\": \"value\", \"dataType\": \"string\"},
              {\"objectKey\": \"type\",\"objectType\": \"object\", \"index\": \"0\",
                             \"dataKey\": \"text\", \"dataType\": \"string\"}]
   }]}"],
  occurs: "-1"}
 ]
}]

