# general properties
server:
  port: 8095
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://localhost:8092
  training: http://localhost
  event-data: http://localhost:8093
  ml-train-goals: =/train/goals/<from>/<to>/<receipt>
  ml-train-assists: /train/assists/<from>/<to>/<receipt>
  ml-train-saves: /train/saves/<from>/<to>/<receipt>
  ml-train-minutes: /train/minutes/<from>/<to>/<receipt>
  ml-train-conceded.: /train/conceded/<from>/<to>/<receipt>
  ml-train-red: /train/red-card/<from>/<to>/<receipt>
  ml-train-yellow: /train/yellow-card/<from>/<to>/<receipt>

#MongoDB Properties
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/predictor-db


training:
  interval: 1
  player-delay: 400
  delay: 1

