# general properties
server:
  port: 8095
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://localhost:8092
  training: http://localhost
  message:
  ml-train-goals: /train/goals/<from>/<to>/<receipt>
  ml-train-assists: /train/assists/<from>/<to>/<receipt>
  ml-train-yellow: /train/yellow-card/<from>/<to>/<receipt>

connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-players-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"


training:
  interval: 1
  delay: 1
  create-delay: 3
  update-delay: 500
  load: false
  cutoff:
