version: "3"
services:

  mongo:
    image: mongo:latest
    container_name: predictor-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: predictor-db
    networks:
      predictornet:
        ipv4_address: 172.22.0.16

  mongo-seed:
    image: stefanwalther/mongo-seed
    container_name: mongo-seed
    environment:
      - MONGODB_HOST=172.22.0.16
      - MONGODB_PORT=27017
    volumes:
      - ./db-seed:/data
    depends_on:
      - mongo
    command: [
         "mongorestore --host 172.22.0.16 --port 27017 --db predictor-db -c team /data/team.bson"
    ]
    networks:
      predictornet:
        ipv4_address: 172.22.0.15

  message:
    image: timmytime/predictor-message-reactive:latest
    container_name: predictor-message-reactive
    ports:
      - "8100:8100"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.18

  scraper:
    image: timmytime/predictor-scraper-reactive:latest
    container_name: predictor-scraper-reactive
    ports:
      - "8101:8101"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.19

  event-scraper:
    image: timmytime/predictor-event-scraper-reactive:latest
    container_name: predictor-event-scraper-reactive
    ports:
      - "8102:8102"
    networks:
      predictornet:
        ipv4_address: 172.22.0.20

  data:
    image: timmytime/predictor-data-reactive:latest
    container_name: predictor-data-reactive
    ports:
      - "8103:8103"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.21

  event-data:
    image: timmytime/predictor-event-data-reactive:latest
    container_name: predictor-event-data-reactive
    ports:
      - "8104:8104"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.22

  teams:
    image: timmytime/predictor-teams-reactive:latest
    container_name: predictor-teams-reactive
    ports:
      - "8105:8105"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.23

  team-events:
    image: timmytime/predictor-events-reactive:latest
    container_name: predictor-events-reactive
    ports:
      - "8106:8106"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.24

  players:
    image: timmytime/predictor-players-reactive:latest
    container_name: predictor-players-reactive
    ports:
      - "8107:8107"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.25

  players-events:
    image: timmytime/predictor-players-events-reactive:latest
    container_name: predictor-players-events-reactive
    ports:
      - "8108:8108"
    depends_on:
      - mongo
    networks:
      predictornet:
        ipv4_address: 172.22.0.26

  client:
    image: timmytime/predictor-client-reactive:latest
    container_name: predictor-client-reactive
    ports:
      - "8109:8109"
    networks:
      predictornet:
        ipv4_address: 172.22.0.27

networks:
  predictornet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

