# general properties
server:
  port: 8093
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://localhost:8092

connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-event-data-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"

