# general properties
server:
  port: 8097

connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-scraper-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
  config:
     import:  "optional:configserver:http://172.31.24.130:8888"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://127.0.0.1:8092
  message: http://127.0.0.1:8090

scraper:
  match: "https://www.espn.co.uk/football/match/_/gameId/{game_id}"
  results: "https://www.espn.co.uk/soccer/scoreboard/_/league/{league}/date/{date}"

scheduler:
  retry: 60000
  tracker: 45000