# general properties
server:
  port: 8097

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/predictor-db
  cloud:
    config:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://127.0.0.1:8092
  team: http://127.0.0.1:8090

scraper:
  match: "https://www.espn.co.uk/football/match/_/gameId/{game_id}"
  results: "https://www.espn.co.uk/soccer/scoreboard/_/league/{league}/date/{date}"

scheduler:
  retry: 60000
  tracker: 45000