# general properties
server:
  port: 8097

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/predictor-db

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://127.0.0.1:8092
  team: http://127.0.0.1:8090

results:
  start-date: 2020-07-10

config:
  dir: /tmp/

delays:
  day: 60
  match: 2
