# general properties
server:
  port: 8101

connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-scraper-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
  config:
     import:  "optional:configserver:http://172.31.24.130:8888"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://172.22.0.21:8103
  message: http://172.22.0.18:8100

scraper:
  match: "https://www.espn.co.uk/football/match/_/gameId/{game_id}"
  results: "https://www.espn.co.uk/soccer/scoreboard/_/league/{league}/date/{date}"

scheduler:
  retry: 60000
  tracker: 45000