base:
  aws: True
  aws_url: ""
  aws_bucket: "tabiiki-test"
  local: "/home/timmytime/"
  train_path: "train/<type>/<key>/"
  vocab_path: "vocab/<type>/<key>/"
  country_results_train_history_file: "country-matches-train-history.json"
  country_goals_train_history_file: "country-goals-train-history.json"

learning:

  match_result:

   default:
     batch_size: 100
     steps: 1000
     hash_bins: 10000
     hidden_units: [10, 20, 10]
     evaluate: False

  match_goals:
    default:
      batch_size: 100
      steps: 1000
      hash_bins: 10000
      hidden_units: [10, 20, 10]
      evaluate: False

analysis:
  team_model_url: ":8090/api/prediction/ml-data/competition/"
  types_url: ":8090/api/prediction/cache/types"
  countries_url: ":8090/api/prediction/cache/countries"
  comps_by_country_url: ":8090/api/prediction/cache/competition-count"

receipt:
  train_receipt_url: ":8090/api/prediction/ml-data/train/receipt"
  predict_receipt_url: ":8090/api/prediction/ml-data/predict/receipt"
