base:
  aws: True
  aws_url: ""
  aws_bucket: "predictor-team-models"
  local: "/home/ubuntu/res/"
  train_path: "train/<key>/"
  vocab_path: "vocab/<key>/"

learning:

  match_result:
    default:
      batch_size: 250
      steps: 1000
      hash_bins: 1000
      hidden_units: [10, 20, 10]
      evaluate: True


  match_goals:
    default:
      batch_size: 250
      steps: 1000
      hash_bins: 1000
      hidden_units: [10, 20, 10]
      evaluate: True


analysis:
  team_model_url: "http://ip-172-31-38-2.ec2.internal:8080/data/"

receipt:
  train_receipt_url: "http://ip-172-31-38-2.ec2.internal:8080/training"
  predict_receipt_url: "http://ip-172-31-40-214.ec2.internal:8080/prediction"

