sportScrapers: [
{siteRules: [
 {id: "german_1",
  url: "http://www.espn.com/soccer/standings/_/league/ger.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 19,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "german_2",
  url: "http://www.espn.com/soccer/standings/_/league/ger.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 19,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "france_1",
  url: "http://www.espn.com/soccer/standings/_/league/fra.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 21,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "france_2",
  url: "http://www.espn.com/soccer/standings/_/league/fra.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 21,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "italy_1",
  url: "http://www.espn.com/soccer/standings/_/league/ita.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 21,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "italy_2",
  url: "http://www.espn.com/soccer/standings/_/league/ita.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 23,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "spain_1",
  url: "http://www.espn.com/soccer/standings/_/league/esp.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 21,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "spain_2",
  url: "http://www.espn.com/soccer/standings/_/league/esp.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 23,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "turkey_1",
  url: "http://www.espn.com/soccer/standings/_/league/tur.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 19,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "england_1",
  url: "http://www.espn.com/soccer/standings/_/league/eng.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 21,  \"tdIdx\": 1}"],
  occurs: "1"} ,
 {id: "england_2",
  url: "http://www.espn.com/soccer/standings/_/league/eng.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 25,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "england_3",
  url: "http://www.espn.com/soccer/standings/_/league/eng.3",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 25,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "england_4",
  url: "http://www.espn.com/soccer/standings/_/league/eng.4",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 25,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "england_5",
  url: "http://www.espn.com/soccer/standings/_/league/eng.5",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 25,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "scotland_1",
  url: "http://www.espn.com/soccer/standings/_/league/sco.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 13,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "scotland_2",
  url: "http://www.espn.com/soccer/standings/_/league/sco.2",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 11,  \"tdIdx\": 1}"],
  occurs: "1"} ,
 {id: "scotland_3",
  url: "http://www.espn.com/soccer/standings/_/league/sco.3",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 11,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "scotland_4",
  url: "http://www.espn.com/soccer/standings/_/league/sco.4",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 11,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "holland_1",
  url: "http://www.espn.com/soccer/standings/_/league/ned.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 19,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "belgium_1",
  url: "http://www.espn.com/soccer/standings/_/league/bel.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody[1]/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 7,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "belgium_1",
  url: "http://www.espn.com/soccer/standings/_/league/bel.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody[2]/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 7,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "portugal_1",
  url: "http://www.espn.com/soccer/standings/_/league/por.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 19,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "sweden_1",
  url: "http://www.espn.com/soccer/standings/_/league/swe.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 17,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "norway_1",
  url: "http://www.espn.com/soccer/standings/_/league/nor.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 17,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "denmark_1",
  url: "http://www.espn.com/soccer/standings/_/league/den.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 15,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "russia_1",
  url: "http://www.espn.com/soccer/standings/_/league/rus.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 17,  \"tdIdx\": 1}"],
  occurs: "1"},
 {id: "greece_1",
  url: "http://www.espn.com/soccer/standings/_/league/gre.1",
  active: "true",
  xpath: "//*[@id=\"main-container\"]/div/section/div[divIdx]/div/div[div2Idx]/table/tbody/tr[trIdx]/td[tdIdx]/a[2]/span/span/text()",
  index: "trIdx",
  ranges: [
   "{\"divIdx\": 1, \"div2Idx\": 2, \"trIdx\": 17,  \"tdIdx\": 1}"],
  occurs: "1"}
 ]}
]