base:
  aws: True
  aws_url: ""
  aws_bucket: "predictor-player-models"
  local: "/home/timmy/"
  train_path: "train/"
  vocab_path: "vocab/"

learning:

  goals:

    default:
      batch_size: 500
      steps: 1000
      hash_bins: 1000
      hidden_units: [10, 20, 10]
      evaluate: True

  assists:

    default:
      batch_size: 500
      steps: 1000
      hash_bins: 1000
      hidden_units: [10, 20, 10]
      evaluate: True

  yellow:

    default:
      batch_size: 500
      steps: 1000
      hash_bins: 1000
      hidden_units: [10, 20, 10]
      evaluate: True


analysis:
  team_model_url: "http://ip-172-31-42-43.ec2.internal:8095/api/prediction/players/ml-data"

receipt:
  train_receipt_url: "http://ip-172-31-42-43.ec2.internal:8095/api/prediction/players/train/receipt"
  predict_receipt_url: "http://ip-172-31-42-43.ec2.internal:8095/api/prediction/players/predict/receipt"

