specialCases: [
{name: "Chievo Verona", alias: "Chievo"},
{name: "Hellas Verona", alias: "Verona"},
{name: "Internazionale", alias: "Inter"},
{name: "Ajax Amsterdam", alias: "Ajax"},
{name: "PSV Eindhoven", alias: "PSV"},
{name: "Desportivo Aves", alias: "Aves"},
{name: "Desportivo Aves", alias: "CD Aves"},
{name: "Deportivo La Coruna", alias: "La Coruna"},
{name: "Sevilla FC", alias: "Sevilla"},
{name: "Chester FC", alias: "Chester"},
{name: "Paris Saint-Germain", alias: "PSG"},
{name: "Wolverhampton Wanderers", alias: "Wolves"},
{name: "Sheffield United", alias: "Sheffield Utd"},
{name: "Cambridge United", alias: "Cambridge Utd"},
{name: "Oxford United", alias: "Oxford Utd"},
{name: "Kuban", alias: "Kuban Krasnodar"},
{name: "Sandnes", alias: "Sandnes Ulf"},
{name: "Laval", alias: "Stade Laval"},
{name: "Istres", alias: "FC Istres"},
{name: "Creteil", alias: "Créteil"},
{name: "York", alias: "York City"},
{name: "Bastia", alias: "CA Bastia"},
{name: "Cambuur", alias: "SC Cambuur"},
{name: "Dusseldorf", alias: "Fortuna Düsseldorf"},
{name: "Dusseldorf", alias: "Fortuna Dusseldorf"},
{name: "Munich 1860", alias: "TSV 1860 Munich"},
{name: "Brondby", alias: "Brøndby"},
{name: "Viborg", alias: "Viborg FF"},
{name: "G.A. Eagles", alias: "Go Ahead Eagles"},
{name: "Karlsruher", alias: "Karlsruher SC"},
{name: "Karlsruher", alias: "Karlsruhe"},
{name: "Oud-Heverlee Leuven", alias: "OH Leuven"},
{name: "Cercle Brugge", alias: "Cercle Brugge KSV"},
{name: "Queen's Park", alias: "Queen&#39;s Park"},
{name: "Braintree", alias: "Braintree Town"},
{name: "Salisbury", alias: "Salisbury City"},
{name: "Kidderminster", alias: "Kidderminster Harriers"},
{name: "Alfreton", alias: "Alfreton Town"},
{name: "Mons", alias: "RAEC Bergen Mons"},
{name: "Charleroi", alias: "Royal Charleroi SC"},
{name: "Charleroi", alias: "Royal Charleroi"},
{name: "Cottbus", alias: "Energie Cottbus"},
{name: "Hereford", alias: "Hereford United"},
{name: "Nuneaton", alias: "Nuneaton Town"},
{name: "Paderborn", alias: "SC Paderborn 07"},
{name: "Sabadell", alias: "CD Sabadell"},
{name: "Reggina 1914", alias: "Reggina"},
{name: "Evian TG", alias: "Evian Thonon Gaillard"},
{name: "Rizespor", alias: "Caykur Rizespor"},
{name: "PAOK", alias: "PAOK Salonika"},
{name: "Nijmegen", alias: "NEC Nijmegen"},
{name: "Eskisehirspor", alias: "Eskisehirspor K"},
{name: "Xanthi", alias: "FC Xanthi"},
{name: "Asteras T.", alias: "Asteras Tripoli"},
{name: "Kalloni", alias: "Kalloni AEL"},
{name: "Smyrnis", alias: "Apollon Smyrni"},
{name: "Nijmegen", alias: "NEC Nijmegen"},
{name: "Academica", alias: "Academica de Coimbra"},
{name: "T. Moscow", alias: "FK Torpedo Moscow"},
{name: "Aalen", alias: "VfR Aalen"},
{name: "Vestsjaelland", alias: "FC Vestsjaelland"},
{name: "Atvidabergs", alias: "Atvidabergs FF"},
{name: "Gefle", alias: "Gefle IF"},
{name: "Falkenbergs", alias: "Falkenbergs FF"},
{name: "Cédric", alias: "Cédric Soares"},
{name: "Telford", alias: "AFC Telford United"},
{name: "Saúl", alias: "Saúl Ñíguez"},
{name: "Rec. Huelva", alias: "Recreativo Huelva"},
{name: "Santander", alias: "Racing Santander"},
{name: "Dordrecht", alias: "Dordrecht &#39;90"},
{name: "Westerlo", alias: "KVC Westerlo"},
{name: "Genk", alias: "Racing Genk"},
{name: "Silkeborg", alias: "Silkeborg IF"},
{name: "M. Saransk", alias: "Mordovia Saransk"},
{name: "St. Liege", alias: "Standard Liege"},
{name: "Gent", alias: "KAA Gent"},
{name: "Penafiel", alias: "FC Penafiel"},
{name: "Nacional", alias: "CD Nacional de Madeira"},
{name: "Nacional", alias: "CD Nacional Madeira"},
{name: "Ath. Bilbao B", alias: "Athletic Bilbao B"},
{name: "Mersin", alias: "Mersin Idmanyurdu"},
{name: "Bourg Peronnas", alias: "Bourg-Peronnas"},
{name: "North Ferriby", alias: "North Ferriby United"},
{name: "Viking", alias: "Viking FK"},
{name: "Tomsk", alias: "FK Tom Tomsk" },
{name: "Jaen", alias: "Real Jaen CF"},
{name: "Volga N. Novgorod", alias: "Volga Nizhny Novgorod"},
{name: "Syrianska", alias: "Syrianska FC"},
{name: "Waalwijk", alias: "RKC Waalwijk"},
{name: "Gijon", alias: "Sporting Gijón"},
{name: "FK Rostov", alias: "Rostov"},
{name: "Nijmegen", alias: "NEC Nijmegen"},
{name: "Kalloni", alias: "Kalloni AEL"},
{name: "Jonkopings", alias: "Jonkopings Sodra"},
{name: "AEK", alias: "AEK Athens"},
{name: "AEL Larissa", alias: "Larissa FC"},
{name: "St. Gilloise", alias: "Union St.-Gilloise"},
{name: "Halmstad", alias: "Halmstads BK"},
{name: "U. Madeira", alias: "Uniao da Madeira"},
{name: "Orenburg", alias: "Gazovik Orenburg"},
{name: "Quevilly Rouen", alias: "US Quevilly"},
{name: "Akhisar Belediyespor", alias: "Akhisar Belediye"},
{name: "Jerv", alias: "FK Jerv"},
{name: "Yenisey", alias: "Yenisey Krasnoyarsk"},
{name: "Helsingor", alias: "FC Helsingor"},
{name: "Graafschap", alias: "De Graafschap"},
{name: "Giannina", alias: "Pas Giannina"},
{name: "Mjondalen", alias: "Mjondalen IF"},
{name: "Odense Boldklub", alias: "Odense BK" },
{name: "Esbjerg FB", alias: "Esbjerg"},
{name: "Ostersunds FK", alias: "Östersunds FK"},
{name: "Lyn", alias: "Lyn Oslo"},
{name: "Salamanca", alias: "U.D. Salamanca"},
{name: "Khimki", alias: "FC Khimki"},
{name: "Saturn Ramenskoye", alias: "Saturn Moscow"},
{name: "Nalchik", alias: "Spartak Nalchik"},
{name: "Orgryte", alias: "Orgryte IS"},
{name: "Aachen", alias: "Alemannia Aachen"},
{name: "Oberhausen", alias: "RW Oberhausen"},
{name: "Vannes", alias: "Vannes OC"},
{name: "Stockport", alias: "Stockport County"},
{name: "Kettering", alias: "Kettering Town"},
{name: "Grays", alias: "Grays Athletic"},
{name: "Rushden", alias: "Rushden & Diamonds"},
{name: "Eastbourne", alias: "Eastbourne Borough"},
{name: "Roeselare", alias: "KSV Roeselare"},
{name: "Koblenz", alias: "TUS Koblenz"},
{name: "Rostock", alias: "Hansa Rostock"},
{name: "Mouscron", alias: "Royal Excelsior Mouscron"},
{name: "Naval", alias: "Naval 1º Maio"},
{name: "Leiria", alias: "Uniao Leiria"},
{name: "Cartagena", alias: "FC Cartagena"},
{name: "R. Union", alias: "Real Unión Irun"},
{name: "Sibir", alias: "Sibir Novosibirsk"},
{name: "Vladikavkaz", alias: "Alania Vladikavkaz"},
{name: "Osnabruck", alias: "VfL Osnabruck"},
{name: "Osnabruck", alias: "VFL Osnabruck"},
{name: "Portogruaro", alias: "Portosummaga"},
{name: "O. Volos", alias: "Olympiacos Volou"},
{name: "Xerez CD", alias: "Xerez"},
{name: "Lov Ham", alias: "Lov-Ham"},
{name: "Dramas", alias: "Doxa Dramas"},
{name: "Ull/Kisa", alias: "Ullensaker/Kisa"},
{name: "Hull City", alias: "Hull"},
{name: "Manchester United", alias: "Man Utd"},
{name: "Manchester United", alias: "Manchester Utd"},
{name: "Brighton & Hove Albion", alias: "Brighton"},
{name: "FC Emmen", alias: "FC Emmen VV"},
{name: "FC Emmen", alias: "Emmen"},
{name: "Sittard", alias: "Fortuna Sittard"},
{name: "Rangers", alias: "Rangers FC"},
{name: "Cádiz", alias: "CF Cadiz"},
{name: "Málaga", alias: "Malaga"},
{name: "AD Alcorcon", alias: "Alcorcon"},
{name: "Gimnastic de Tarragona", alias: "Gimnastic Tarragona"},
{name: "Mallorca", alias: "RCD Mallorca"},
{name: "Osasuna", alias: "CA Osasuna"},
{name: "Albion Rovers", alias: "Albion"},
{name: "Goztepe", alias: "Goztepe SK"},
{name: "Erzurum BB", alias: "BB Erzurumspor"},
{name: "Ural Sverdlovsk Oblast", alias: "Ural Ekaterinburg"},
{name: "Orenburg", alias: "FC Orenburg"},
{name: "Yenisey", alias: "FK Yenisey"},
{name: "Krylia Sovetov", alias: "Kryliya Sovetov Samara"},
{name: "Feyenoord Rotterdam", alias: "Feyenoord"},
{name: "GD Chaves", alias: "Desportivo Chaves"},
{name: "Antwerp", alias: "Royal Antwerp"},
{name: "Mouscron", alias: "Royal Excel Mouscron"},
{name: "Charleroi", alias: "Sporting Charleroi"},
{name: "KV Oostende", alias: "Oostende"},
{name: "Zulte-Waregem", alias: "Zulte Waregem"},
{name: "Valerenga", alias: "Vålerenga IF"},
{name: "Sandefjord", alias: "Sandefjord Fotball"},
{name: "Lillestrom", alias: "Lillestrom Sk"},
{name: "Stromsgodset", alias: "Stromsgodset IF"},
{name: "AGF Aarhus", alias: "Aarhus GF"},
{name: "Stabaek", alias: "Stabaek IF"},
{name: "Molde", alias: "Molde FK"},
{name: "Moreirense", alias: "Moreirense FC"},
{name: "Vendsyssel", alias: "Vendsyssel FF"},
{name: "Strasbourg", alias: "Racing Strasbourg"},
{name: "Nimes", alias: "Olympique Nimes"},
{name: "Paris FC", alias: "Paris"},
{name: "Stirling Albion", alias: "Stirling"},
{name: "Aris Salonika", alias: "Aris"},
{name: "Deportivo La Coruña", alias: "Deportivo La Coruna"},
{name: "Gijon", alias: "Sporting Gijon"},
{name: "Saint-Etienne", alias: "St. Etienne"},
{name: "Sheffield United", alias: "Sheff Utd"},
{name: "Sheffield Wednesday", alias: "Sheff Wed"},
{name: "Nottingham Forest", alias: "Nottm Forest"},
{name: "Alavés", alias: "Alaves"},
{name: "Queens Park Rangers", alias: "QPR"},
{name: "Cádiz", alias: "Cadiz"},
{name: "Cordoba", alias: "CF Cordoba"},
{name: "Cordoba", alias: "Córdoba"},
{name: "Málaga", alias: "Malaga"},
{name: "Numancia", alias: "CD Numancia"},
{name: "Leganes", alias: "CD Leganes"},
{name: "FC Arsenal Tula", alias: "Arsenal Tula"},
{name: "SC Heracles Almelo", alias: "Heracles Almelo"},
{name: "Heerenveen", alias: "SC Heerenveen"},
{name: "Zulte-Waregem", alias: "SV Zulte Waregem"},
{name: "Boavista", alias: "Boavista Porto"},
{name: "Santa Clara", alias: "CD Santa Clara"},
{name: "Maritimo", alias: "Maritimo Madeira"},
{name: "Sarpsborg FK", alias: "Sarpsborg 08"},
{name: "Saint-Etienne", alias: "St Etienne"},
{name: "AS Nancy Lorraine", alias: "AS Nancy-Lorraine"},
{name: "Le Havre AC", alias: "Le Havre"},
{name: "Grenoble", alias: "Grenoble Foot"},
{name: "Niort", alias: "Chamois Niort"},
{name: "Beziers AS", alias: "AS Beziers"},
{name: "Internazionale", alias: "Inter Milan"},
{name: "SPAL", alias: "SPAL 2013"},
{name: "Cittadella", alias: "AS Cittadella"},
{name: "Dundee", alias: "Dundee FC"},
{name: "Queen's Park", alias: "Queens Park"},
{name: "Valerenga", alias: "Vålerenga"},
{name: "Orléans", alias: "Orleans"},
{name: "Osters IF", alias: "Osters"},
{name: "FC Cologne", alias: "FC Koln"},
{name: "Tromso", alias: "Tromsø"},
{name: "FC Magdeburg", alias: "1. FC Magdeburg"},
{name: "Dundee United", alias: "Dundee Utd"},
{name: "FC Ufa", alias: "Ufa"},
{name: "Anderlecht", alias: "RSC Anderlecht"},
{name: "Elche", alias: "CF Elche"},
{name: "Cosenza", alias: "Cosenza Calcio"},
{name: "GD Chaves", alias: "Desportivo Chaves"},
{name: "Las Palmas", alias: "UD Las Palmas"},
{name: "Tenerife", alias: "CD Tenerife"},
{name: "Numancia", alias: "CD Numancia"},
{name: "Huesca", alias: "SD Huesca"},
{name: "Spartak Moscow", alias: "Spartak"},
{name: "Sint-Truidense", alias: "Sint-Truiden"},
{name: "Lugo", alias: "CD Lugo"},
{name: "Maidenhead Utd", alias: "Maidenhead United"},
{name: "Dover", alias: "Dover Athletic"},
{name: "Halifax", alias: "Halifax Town"},
{name: "SV Darmstadt 98", alias: "SV Darmstadt"},
{name: "SV Darmstadt 98", alias: "Darmstadt"},
{name: "Hamburg SV", alias: "Hamburger SV"},
{name: "Brighton & Hove Albion", alias: "Brighton and Hove Albion"},
{name: "1. FC Heidenheim", alias: "FC Heidenheim"},
{name: "1. FC Heidenheim", alias: "Heidenheim"},
{name: "Troyes", alias: "ESTAC Troyes"},
{name: "Millwall", alias: "Millwall FC"},
{name: "Preston North End", alias: "Preston"},
{name: "IFK", alias: "IFK Goteborg"},
{name: "Orebro SK", alias: "Orebro"},
{name: "Helsingborg", alias: "Helsingborgs"},
{name: "IFK Norrkoping", alias: "Norrkoping"},
{name: "AFC Eskilstuna", alias: "AFC Utd"},
{name: "Krasnodar", alias: "FK Krasnodar"},
{name: "FC Tambov", alias: "FK Tambov"},
{name: "Krylia Sovetov", alias: "Kryliya Sovetov"},
{name: "Sochi", alias: "PFC Sochi"},
{name: "Wehen Wiesbaden", alias: "SV Wehen Wiesbaden"},
{name: "Rodez Aveyron", alias: "Rodez"},
{name: "Chambly Oise", alias: "FC Chambly"},
{name: "Hertha Berlin", alias: "Hertha BSC"},
{name: "Borussia Monchengladbach", alias: "Borussia M'gladbach"},
{name: "Schalke 04", alias: "Schalke"},
{name: "Nurnberg", alias: "Nuremberg"},
{name: "Famalicao", alias: "FC Famalicao"},
{name: "Odense Boldklub", alias: "OB"},
{name: "Pordenone", alias: "Pordenone Calcio"},
{name: "Eupen", alias: "AS Eupen"},
{name: "ADO Den Haag", alias: "Den Haag"},
{name: "VVV Venlo", alias: "VVV-Venlo"},
{name: "Istanbul Basaksehir", alias: "Basaksehir"},
{name: "Gazisehir Gaziantep", alias: "Gaziantep FK"},
{name: "Smirnis", alias: "Apollon Smirnis"},
{name: "Asteras T.", alias: "Asteras Tripolis"},
{name: "Panetolikos", alias: "Panaitolikos"},
{name: "Giannina", alias: "PAS Giannina"},
{name: "FK Rubin Kazan", alias: "Rubin Kazan"},
{name: "VfL Bochum", alias: "Bochum"},
{name: "Paderborn", alias: "Paderborn 07"},
{name: "SV Sandhausen", alias: "Sandhausen"},
{name: "SpVgg Greuther Furth", alias: "Greuther Furth"},
{name: "SSV Jahn Regensburg", alias: "Jahn Regensburg"},
{name: "TSV Eintracht Braunschweig", alias: "Eintracht Braunschweig"},
{name: "TSV Eintracht Braunschweig", alias: "Braunschweig"},
{name: "Würzburger Kickers", alias: "FC Wurzburger Kickers"},
{name: "Würzburger Kickers", alias: "Wurzburger Kickers"},
{name: "FC Erzgebirge Aue", alias: "Erzgebirge Aue"},
{name: "Venezia FC", alias: "Venezia"}

]