# general properties
server:
  port: 8108
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://172.22.0.21:8103
  training: http://172.22.0.18:8100/players
  event-data: http://172.22.0.22:8104
  message: http://172.22.0.18:8100
  ml-predict-goals: /predict/goals/<init>/<receipt>
  ml-predict-assists: /predict/assists/<init>/<receipt>
  ml-predict-yellow: /predict/yellow-card/<init>/<receipt>
  ml-predict-init: /predict/init/<type>
  ml-predict-destroy: /predict/clear-down/<type>


connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-players-events-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"

training:
  interval: 1
  player-delay: 400
  delay: 1

