# general properties
server:
  port: 8100
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://localhost:8092
  event: http://localhost:8094
  event-data: http://localhost:8093
  players: http://localhost:8095
  data-scraper:
  event-scraper:

delays:
  delay: 1
  start: 3

orchestration:
  enabled: false

vocab:
  players: true
  teams: false

betting:
   home-win: 75
   away-win: 50
   draw: 40
   goal: 50
   assist: 40
   yellow-card: 50
