# general properties
server:
  port: 8109
springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: predictor-client-reactive
  config:
    import: "optional:configserver:http://172.31.24.130:8888"


clients:
  data: http://172.22.0.21:8103
  event-data: http://172.22.0.22:8104
  events: http://172.22.0.24:8106
  player-events: http://172.22.0.26:8108
  message: http://172.22.0.18:8100

delays:
  delay: 1
  start: 3

orchestration:
  enabled: false

vocab:
  players: false
  teams: false

betting:
  home-win: 75
  away-win: 50
  draw: 40
  goal: 50
  assist: 40
  yellow-card: 50

test:
  mode: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
