# general properties
server:
  port: 8098

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://127.0.0.1:8092
  event-data: http://127.0.0.1:8093
  events: http://127.0.0.1:8091

# default properties
config:
  dir: /tmp/

delays:
  betway: 1
  paddypower: 1
  paddypower2: 60

