# general properties
server:
  port: 8102

spring:
  application:
    name: predictor-event-scraper-reactive
  config:
    import: "optional:configserver:http://172.31.24.130:8888"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  event-data: http://172.22.0.22:8104
  message: http://172.22.0.18:8100

fixtures:
  url: "https://www.espn.co.uk/soccer/fixtures/_/date/{date}/league/{competition}"

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
