# general properties
server:
  port: 8098

spring:
  application:
    name: predictor-event-scraper-reactive
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data: http://127.0.0.1:8092
  event-data: http://127.0.0.1:8093
  message: http://127.0.0.1:8091

fixtures:
  url: "https://www.espn.co.uk/soccer/fixtures/_/date/{date}/league/{competition}"
