bookmakerScrapers: [
{siteRules: [
{ type: "leagues",
  order: "-1",
  id: "generic",
  keys: ["SubCategoryCName", "GroupCName"],
  url: "https://sports.betway.com/api/Events/V2/GetGroup?t=f3d60cf5-66d5-4828-a944-8fa1f3314d7f",
  payload: "{\"PremiumOnly\":false,\"LanguageId\":1,\"ClientTypeId\":2,\"BrandId\":3,\"JurisdictionId\":1,
              \"ClientIntegratorId\":1,\"CategoryCName\":\"soccer\",\"SubCategoryCName\":\"england\",
              \"GroupCName\":\"championship\",\"ApplicationId\":5,\"BrowserId\":3,\"OsId\":5,
              \"ApplicationVersion\":\"\",\"BrowserVersion\":\"65.0.3325.181\",\"OsVersion\":null,
              \"SessionId\":null,\"TerritoryId\":227,\"ViewName\":\"sports\"}",
  active: "true",
  extractConfig: "{ \"list\": \"EventSummaries\",
                     \"key\": \"EventId\"}"
},
{ type: "events",
  id: "generic",
  keys: ["EventId"],
  url: "https://sports.betway.com/api/Events/V2/GetEventDetails?t=511f09cf-2940-48e2-af29-b32279c06b87",
  payload: "{\"EventId\":2271325,\"LanguageId\":1,\"ClientTypeId\":2,\"BrandId\":3,\"JurisdictionId\":1,
               \"ClientIntegratorId\":1,\"ScoreboardRequest\":{\"ScoreboardType\":0,\"IncidentRequest\":{}},
               \"ApplicationId\":5,\"BrowserId\":3,\"OsId\":5,\"ApplicationVersion\":\"\",
               \"BrowserVersion\":\"65.0.3325.181\",\"OsVersion\":null,\"SessionId\":null,\"TerritoryId\":227,
               \"ViewName\":\"sports\"}",
  active: "true",
  extractConfig: "{ \"event\": \"Event\",
                      \"eventValues\": [{\"key\": \"HomeTeamName\"},
                                        {\"key\": \"AwayTeamName\"},
                                        {\"key\": \"Milliseconds\"}],
                     \"markets\": \"Markets\",
                     \"marketValues\": \"Outcomes\",
                     \"outcomes\": \"Outcomes\",
                      \"outcomeValues\": [{\"key\": \"BetName\"},
                                          {\"key\": \"CouponName\"},
                                          {\"key\": \"OddsDecimal\"}]}"
},
{ type: "leagues",
  id: "england_1",
  order: "1000",
  url: "",
  keys: ["{\"SubCategoryCName\":\"england\"}","{\"GroupCName\": \"premier-league\"}"],
  active: "true"
},
{ type: "leagues",
  id: "england_2",
  order: "1001",
  url: "",
  keys: ["{\"SubCategoryCName\":\"england\"}","{\"GroupCName\": \"championship\"}"],
  active: "true"
},
{ type: "leagues",
  id: "england_3",
  order: "1002",
  url: "",
  keys: ["{\"SubCategoryCName\":\"england\"}","{\"GroupCName\": \"league-one\"}"],
  active: "true"
},
{ type: "leagues",
  id: "england_4",
  order: "1003",
  url: "",
  keys: ["{\"SubCategoryCName\":\"england\"}","{\"GroupCName\": \"league-two\"}"],
  active: "true"
},
{ type: "leagues",
  id: "spain_1",
  order: "102",
  url: "",
  keys: ["{\"SubCategoryCName\":\"spain\"}","{\"GroupCName\": \"la-liga\"}"],
  active: "true"
},
{ type: "leagues",
  id: "spain_2",
  order: "103",
  url: "",
  keys: ["{\"SubCategoryCName\":\"spain\"}","{\"GroupCName\": \"segunda-division\"}"],
  active: "true"
},
{ type: "leagues",
  id: "turkey_1",
  order: "1",
  url: "",
  keys: ["{\"SubCategoryCName\":\"turkey\"}","{\"GroupCName\": \"super-lig\"}"],
  active: "true"
},
{ type: "leagues",
  id: "russia_1",
  order: "7",
  url: "",
  keys: ["{\"SubCategoryCName\":\"russia\"}","{\"GroupCName\": \"premier-league\"}"],
  active: "true"
},
{ type: "leagues",
  id: "holland_1",
  order: "2",
  url: "",
  keys: ["{\"SubCategoryCName\":\"netherlands\"}","{\"GroupCName\": \"eredivisie\"}"],
  active: "true"
},
{ type: "leagues",
  id: "belgium_1",
  order: "3",
  url: "",
  keys: ["{\"SubCategoryCName\":\"belgium\"}","{\"GroupCName\": \"first-division-a\"}"],
  active: "true"
},
{ type: "leagues",
  id: "portugal_1",
  order: "4",
  url: "",
  keys: ["{\"SubCategoryCName\":\"portugal\"}","{\"GroupCName\": \"primeira-liga\"}"],
  active: "true"
},
{ type: "leagues",
  id: "norway_1",
  order: "5",
  url: "",
  keys: ["{\"SubCategoryCName\":\"norway\"}","{\"GroupCName\": \"eliteserien\"}"],
  active: "true"
},
{ type: "leagues",
  id: "denmark_1",
  order: "6",
  url: "",
  keys: ["{\"SubCategoryCName\":\"denmark\"}","{\"GroupCName\": \"superligaen\"}"],
  active: "true"
},
{ type: "leagues",
  id: "france_1",
  order: "106",
  url: "",
  keys: ["{\"SubCategoryCName\":\"france\"}","{\"GroupCName\": \"ligue-1\"}"],
  active: "true"
},
{ type: "leagues",
  id: "france_2",
  order: "107",
  url: "",
  keys: ["{\"SubCategoryCName\":\"france\"}","{\"GroupCName\": \"ligue-2\"}"],
  active: "true"
},
{ type: "leagues",
  id: "italy_1",
  order: "104",
  url: "",
  keys: ["{\"SubCategoryCName\":\"italy\"}","{\"GroupCName\": \"serie-a\"}"],
  active: "true"
},
{ type: "leagues",
  id: "italy_2",
  order: "105",
  url: "",
  keys: ["{\"SubCategoryCName\":\"italy\"}","{\"GroupCName\": \"serie-b\"}"],
  active: "true"
},
{ type: "leagues",
  id: "german_1",
  order: "100",
  url: "",
  keys: ["{\"SubCategoryCName\":\"germany\"}","{\"GroupCName\": \"bundesliga\"}"],
  active: "true"
},
{ type: "leagues",
  id: "german_2",
  order: "101",
  url: "",
  keys: ["{\"SubCategoryCName\":\"germany\"}","{\"GroupCName\": \"2-bundesliga\"}"],
  active: "true"
},
{ type: "leagues",
  id: "scotland_1",
  order: "1004",
  url: "",
  keys: ["{\"SubCategoryCName\":\"scotland\"}","{\"GroupCName\": \"premiership\"}"],
  active: "true"
},
{ type: "leagues",
  id: "scotland_2",
  order: "1005",
  url: "",
  keys: ["{\"SubCategoryCName\":\"scotland\"}","{\"GroupCName\": \"championship\"}"],
  active: "true"
},
{ type: "leagues",
  id: "scotland_3",
  order: "1006",
  url: "",
  keys: ["{\"SubCategoryCName\":\"scotland\"}","{\"GroupCName\": \"league-one\"}"],
  active: "true"
},
{ type: "leagues",
  id: "scotland_4",
  order: "1007",
  url: "",
  keys: ["{\"SubCategoryCName\":\"scotland\"}","{\"GroupCName\": \"league-two\"}"],
  active: "true"
}
]
}
]