# general properties
server:
  port: 8092

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/predictor-db
      auto-index-creation: true

config:
  dir: ./src/main/resources/config/

data:
  missing:
    countries:
      - country: "england"
        competitions:
          - competition: "england_1"
            teams: ""
          - competition: "england_2"
            teams: ""
          - competition: "england_3"
            teams: ""
          - competition: "england_4"
            teams: ""
          - competition: "england_1"
            teams: "Harrogate Town,"
      - country: "scotland"
        competitions:
          - competition: "scotland_1"
            teams: ""
          - competition: "scotland_2"
            teams: ""
          - competition: "scotland_3"
            teams: ""
          - competition: "scotland_4"
            teams: ""
      - country: "spain"
        competitions:
          - competition: "spain_1"
            teams: ""
          - competition: "spain_2"
            teams: "Castellón,"
      - country: "italy"
        competitions:
          - competition: "italy_1"
            teams: ""
          - competition: "italy_2"
            teams: "Reggiana,"
      - country: "france"
        competitions:
          - competition: "france_1"
            teams: ""
          - competition: "france_2"
            teams: "Pau,Dunkerque,"
      - country: "german"
        competitions:
          - competition: "german_1"
            teams: ""
          - competition: "german_2"
            teams: ""
      - country: "portugal"
        competitions:
          - competition: "portugal_1"
            teams: "SC Farense,"
      - country: "holland"
        competitions:
          - competition: "holland_1"
            teams: ""
      - country: "belgium"
        competitions:
          - competition: "belgium_1"
            teams: ""
      - country: "denmark"
        competitions:
          - competition: "denmark_1"
            teams: ""
      - country: "russia"
        competitions:
          - competition: "russia_1"
            teams: ""
      - country: "greece"
        competitions:
          - competition: "greece_1"
            teams: "Volos NFC,"
      - country: "turkey"
        competitions:
          - competition: "turkey_1"
            teams: "Fatih Karagümrük,Hatayspor,"
      - country: "norway"
        competitions:
          - competition: "norway_1"
            teams: ""
      - country: "sweden"
        competitions:
          - competition: "sweden_1"
            teams: ""


