# general properties
server:
  port: 8103

springdoc:
  swagger-ui:
    path: /swagger-ui.html

connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-data-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
      auto-index-creation: true
  config:
    import: "optional:configserver:http://172.31.24.130:8888"

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true


