
# general properties
server:
  port: 8100
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data-scraper: http://172.22.0.19:8101
  events-scraper: http://172.22.0.20:8102
  data: http://172.22.0.21:8103
  data-event: http://172.22.0.22:8104
  teams: http://172.22.0.23:8105
  players: http://172.22.0.25:8107
  team-events: http://172.22.0.24:8106
  player-events: http://172.22.0.26:8108
  client:


connection:
  details:
    host: 172.22.0.16
    port: 27017
    database: 'predictor-db'

spring:
  application:
    name: predictor-message-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.host}:${connection.details.port}/${connection.details.database}
      auto-index-creation: true
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"

test:
  mode: true

