
# general properties
server:
  port: 8096
springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  data-scraper: http://localhost:8092
  events-scrapoer: http://localhost:8092
  teams:
  players:
  team-events:
  player-events:
  client:


connection:
  details:
    host: 'localhost'
    port: 27017
    database: 'predictor-db'
    username: 'predictor'
    password: 'predictor'

spring:
  application:
    name: predictor-message-reactive
  data:
    mongodb:
      uri: mongodb://${connection.details.username}:${connection.details.password}@${connection.details.host}:${connection.details.port}/${connection.details.database}?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
  config:
    import:  "optional:configserver:http://172.31.24.130:8888"

