name: Teams Docker Image CI

on:
  push:
    branches: master
    paths: "predictor-teams-reactive/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file predictor-teams-reactive/Dockerfile
