name: Players Events CI

on:
  push:
     branches: 
       - master
     paths:
       - "predictor-players-events-reactive/**"       


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package --file predictor-players-events-reactive/pom.xml
        
