name: Predictor Reactive CI/CD

on:
  push:
     branches: 
       - master      

jobs:
  build-team:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-teams-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-teams-reactive:test predictor-teams-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-teams-reactive:test 

  build-player:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-players-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-players-reactive:test predictor-players-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-players-reactive:test 

  build-player-event:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-players-events-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-players-events-reactive:test predictor-players-events-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-players-events-reactive:test 

  build-event:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-events-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-events-reactive:test predictor-events-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-events-reactive:test 

  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-client-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-client-reactive:test predictor-client-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-client-reactive:test 

  build-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-data-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-data-reactive:test predictor-data-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-data-reactive:test 

  build-event-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-event-data-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-event-data-reactive:test predictor-event-data-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-event-data-reactive:test 

  build-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-scraper-reactive/pom.xml
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: predictor-scraper-reactive/target/site/jacoco/jacoco.csv
          generate-branches-badge: true
          coverage-badge-filename: scraper.svg
      - name: docker build and tag
        run: docker build -t timmytime/predictor-scraper-reactive:test predictor-scraper-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-scraper-reactive:test 

  build-event-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-event-scraper-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-event-scraper-reactive:test predictor-event-scraper-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-event-scraper-reactive:test 

  build-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: mvn build
        run: mvn clean package --file predictor-message-reactive/pom.xml
      - name: docker build and tag
        run: docker build -t timmytime/predictor-message-reactive:test predictor-message-reactive/ 
      - name: docker push
        run: docker push timmytime/predictor-message-reactive:test 


  e2e-smoke-test:
    needs: [build-team, build-player, build-data, build-client, build-message, build-scraper, build-event-scraper, build-event, build-player-event, build-event-data]
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v2
      - name: run e2e smoke test
        run: ./e2e.sh
        shell: bash

  publish-team:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-teams-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-teams-reactive:test timmytime/predictor-teams-reactive:latest
      - name: push
        run: docker push timmytime/predictor-teams-reactive:latest

  publish-player:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-players-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-players-reactive:test timmytime/predictor-players-reactive:latest
      - name: push
        run: docker push timmytime/predictor-players-reactive:latest

  publish-player-event:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-players-events-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-players-events-reactive:test timmytime/predictor-players-events-reactive:latest
      - name: push
        run: docker push timmytime/predictor-players-events-reactive:latest

  publish-event:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-events-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-events-reactive:test timmytime/predictor-events-reactive:latest
      - name: push
        run: docker push timmytime/predictor-events-reactive:latest

  publish-data:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-data-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-data-reactive:test timmytime/predictor-data-reactive:latest
      - name: push
        run: docker push timmytime/predictor-data-reactive:latest

  publish-event-data:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-event-data-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-event-data-reactive:test timmytime/predictor-event-data-reactive:latest
      - name: push
        run: docker push timmytime/predictor-event-data-reactive:latest

  publish-scraper:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-scraper-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-scraper-reactive:test timmytime/predictor-scraper-reactive:latest
      - name: push
        run: docker push timmytime/predictor-scraper-reactive:latest
        
  publish-event-scraper:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-event-scraper-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-event-scraper-reactive:test timmytime/predictor-event-scraper-reactive:latest
      - name: push
        run: docker push timmytime/predictor-event-scraper-reactive:latest

  publish-client:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-client-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-client-reactive:test timmytime/predictor-client-reactive:latest
      - name: push
        run: docker push timmytime/predictor-client-reactive:latest

  publish-message:
    needs: e2e-smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull test image
        run: docker pull timmytime/predictor-message-reactive:test
      - name: tag as latest
        run: docker tag timmytime/predictor-message-reactive:test timmytime/predictor-message-reactive:latest
      - name: push
        run: docker push timmytime/predictor-message-reactive:latest



        
