version: '3'
services:
 data:
    image: timmytime/predictor-event-scraper-reactive:latest
    container_name: predictor-event-scraper-reactive
    environment:
     - "SPRING_PROFILES_ACTIVE=prod"
    ports:
     - "8098:8098"
    networks:
     predictornet:
      ipv4_address: 172.22.0.20
networks:
  predictornet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/16
 
